# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_JBossDeserialVulnTool(object):
    def setupUi(self, JBossDeserialVulnTool):
        JBossDeserialVulnTool.setObjectName("JBossDeserialVulnTool")
        JBossDeserialVulnTool.resize(808, 596)
        self.centralwidget = QtWidgets.QWidget(JBossDeserialVulnTool)
        self.centralwidget.setObjectName("centralwidget")
        self.LEHost = QtWidgets.QLineEdit(self.centralwidget)
        self.LEHost.setGeometry(QtCore.QRect(60, 20, 231, 21))
        self.LEHost.setInputMask("")
        self.LEHost.setText("")
        self.LEHost.setObjectName("LEHost")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 791, 511))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pBCommonPort = QtWidgets.QPushButton(self.tab)
        self.pBCommonPort.setGeometry(QtCore.QRect(454, 450, 81, 23))
        self.pBCommonPort.setAutoDefault(False)
        self.pBCommonPort.setObjectName("pBCommonPort")
        self.pBClearAll = QtWidgets.QPushButton(self.tab)
        self.pBClearAll.setGeometry(QtCore.QRect(680, 450, 75, 23))
        self.pBClearAll.setObjectName("pBClearAll")
        self.pBAllPort = QtWidgets.QPushButton(self.tab)
        self.pBAllPort.setGeometry(QtCore.QRect(570, 450, 81, 23))
        self.pBAllPort.setAutoDefault(False)
        self.pBAllPort.setObjectName("pBAllPort")
        self.tBPortScan = QtWidgets.QTextBrowser(self.tab)
        self.tBPortScan.setGeometry(QtCore.QRect(15, 11, 741, 431))
        self.tBPortScan.setObjectName("tBPortScan")
        self.tabWidget.addTab(self.tab, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.tBDetect = QtWidgets.QTextBrowser(self.widget)
        self.tBDetect.setGeometry(QtCore.QRect(10, 50, 761, 391))
        self.tBDetect.setObjectName("tBDetect")
        self.pBDSend = QtWidgets.QPushButton(self.widget)
        self.pBDSend.setGeometry(QtCore.QRect(560, 450, 75, 23))
        self.pBDSend.setObjectName("pBDSend")
        self.pBDClear = QtWidgets.QPushButton(self.widget)
        self.pBDClear.setGeometry(QtCore.QRect(690, 450, 75, 23))
        self.pBDClear.setObjectName("pBDClear")
        self.PortLabel = QtWidgets.QLabel(self.widget)
        self.PortLabel.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.PortLabel.setObjectName("PortLabel")
        self.PortlineEdit = QtWidgets.QLineEdit(self.widget)
        self.PortlineEdit.setGeometry(QtCore.QRect(130, 20, 141, 21))
        self.PortlineEdit.setObjectName("PortlineEdit")
        self.tabWidget.addTab(self.widget, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pBGetInfo = QtWidgets.QPushButton(self.tab_4)
        self.pBGetInfo.setGeometry(QtCore.QRect(550, 450, 91, 23))
        self.pBGetInfo.setCheckable(True)
        self.pBGetInfo.setObjectName("pBGetInfo")
        self.pBInfoClear = QtWidgets.QPushButton(self.tab_4)
        self.pBInfoClear.setGeometry(QtCore.QRect(670, 450, 91, 23))
        self.pBInfoClear.setObjectName("pBInfoClear")
        self.tBInfoShower = QtWidgets.QTextBrowser(self.tab_4)
        self.tBInfoShower.setGeometry(QtCore.QRect(10, 10, 761, 431))
        self.tBInfoShower.setObjectName("tBInfoShower")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tBcmdresult = QtWidgets.QTextBrowser(self.tab_3)
        self.tBcmdresult.setGeometry(QtCore.QRect(10, 40, 761, 431))
        self.tBcmdresult.setObjectName("tBcmdresult")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 141, 16))
        self.label_2.setObjectName("label_2")
        self.cmdlineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.cmdlineEdit.setGeometry(QtCore.QRect(160, 10, 401, 21))
        self.cmdlineEdit.setObjectName("cmdlineEdit")
        self.pBCmdExec = QtWidgets.QPushButton(self.tab_3)
        self.pBCmdExec.setGeometry(QtCore.QRect(580, 10, 71, 21))
        self.pBCmdExec.setAutoRepeat(True)
        self.pBCmdExec.setObjectName("pBCmdExec")
        self.pBCmdClear = QtWidgets.QPushButton(self.tab_3)
        self.pBCmdClear.setGeometry(QtCore.QRect(670, 10, 71, 21))
        self.pBCmdClear.setObjectName("pBCmdClear")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.pBGenShell = QtWidgets.QPushButton(self.tab_5)
        self.pBGenShell.setGeometry(QtCore.QRect(430, 450, 111, 23))
        self.pBGenShell.setObjectName("pBGenShell")
        self.pBSendShell = QtWidgets.QPushButton(self.tab_5)
        self.pBSendShell.setGeometry(QtCore.QRect(570, 450, 91, 23))
        self.pBSendShell.setObjectName("pBSendShell")
        self.pBShellClear = QtWidgets.QPushButton(self.tab_5)
        self.pBShellClear.setGeometry(QtCore.QRect(690, 450, 81, 23))
        self.pBShellClear.setObjectName("pBShellClear")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.label_3.setObjectName("label_3")
        self.lEUrl = QtWidgets.QLineEdit(self.tab_5)
        self.lEUrl.setGeometry(QtCore.QRect(150, 10, 621, 20))
        self.lEUrl.setInputMask("")
        self.lEUrl.setPlaceholderText("")
        self.lEUrl.setObjectName("lEUrl")
        self.tBShowShell = QtWidgets.QTextBrowser(self.tab_5)
        self.tBShowShell.setGeometry(QtCore.QRect(10, 40, 771, 401))
        self.tBShowShell.setObjectName("tBShowShell")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tWFile = QtWidgets.QTreeWidget(self.tab_6)
        self.tWFile.setGeometry(QtCore.QRect(10, 50, 281, 431))
        self.tWFile.setObjectName("tWFile")
        self.tWFile.headerItem().setText(0, "1")
        self.pBFile = QtWidgets.QPushButton(self.tab_6)
        self.pBFile.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.pBFile.setObjectName("pBFile")
        self.tBFileCon = QtWidgets.QTextBrowser(self.tab_6)
        self.tBFileCon.setGeometry(QtCore.QRect(300, 50, 481, 431))
        self.tBFileCon.setObjectName("tBFileCon")
        self.label_4 = QtWidgets.QLabel(self.tab_6)
        self.label_4.setGeometry(QtCore.QRect(100, 15, 81, 21))
        self.label_4.setObjectName("label_4")
        self.pBShowFile = QtWidgets.QPushButton(self.tab_6)
        self.pBShowFile.setGeometry(QtCore.QRect(680, 10, 91, 31))
        self.pBShowFile.setObjectName("pBShowFile")
        self.tBShowUrl = QtWidgets.QTextBrowser(self.tab_6)
        self.tBShowUrl.setGeometry(QtCore.QRect(190, 10, 471, 31))
        self.tBShowUrl.setObjectName("tBShowUrl")
        self.tabWidget.addTab(self.tab_6, "")
        #JBossDeserialVulnTool.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(JBossDeserialVulnTool)
        self.statusbar.setObjectName("statusbar")
        #JBossDeserialVulnTool.setStatusBar(self.statusbar)

        self.retranslateUi(JBossDeserialVulnTool)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(JBossDeserialVulnTool)

    def retranslateUi(self, JBossDeserialVulnTool):
        _translate = QtCore.QCoreApplication.translate
        JBossDeserialVulnTool.setWindowTitle(_translate("JBossDeserialVulnTool", "JBossDeserialVulnTool"))
        self.LEHost.setPlaceholderText(_translate("JBossDeserialVulnTool", "请输入目标IP地址"))
        self.label.setText(_translate("JBossDeserialVulnTool", "目标："))
        self.pBCommonPort.setText(_translate("JBossDeserialVulnTool", "常用端口扫描"))
        self.pBClearAll.setText(_translate("JBossDeserialVulnTool", "重置"))
        self.pBAllPort.setText(_translate("JBossDeserialVulnTool", "全端口扫描"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("JBossDeserialVulnTool", "端口扫描"))
        self.pBDSend.setText(_translate("JBossDeserialVulnTool", "开始检测"))
        self.pBDClear.setText(_translate("JBossDeserialVulnTool", "清空信息"))
        self.PortLabel.setText(_translate("JBossDeserialVulnTool", "请输入敏感端口："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("JBossDeserialVulnTool", "漏洞检测"))
        self.pBGetInfo.setText(_translate("JBossDeserialVulnTool", "获取信息"))
        self.pBInfoClear.setText(_translate("JBossDeserialVulnTool", "清空信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("JBossDeserialVulnTool", "主机信息"))
        self.label_2.setText(_translate("JBossDeserialVulnTool", "请输入需要执行的命令："))
        self.pBCmdExec.setText(_translate("JBossDeserialVulnTool", "执行"))
        self.pBCmdClear.setText(_translate("JBossDeserialVulnTool", "清空信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("JBossDeserialVulnTool", "虚拟终端"))
        self.pBGenShell.setText(_translate("JBossDeserialVulnTool", "一键生成Webshell"))
        self.pBSendShell.setText(_translate("JBossDeserialVulnTool", "发送Webshell"))
        self.pBShellClear.setText(_translate("JBossDeserialVulnTool", "清空信息"))
        self.label_3.setText(_translate("JBossDeserialVulnTool", "请输入文件上传路径："))
        self.lEUrl.setText(_translate("JBossDeserialVulnTool", "/jboss-6.1.0.Final/server/default/deploy/ROOT.war/shell.jsp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("JBossDeserialVulnTool", "Webshell上传"))
        self.pBFile.setText(_translate("JBossDeserialVulnTool", "获取目录"))
        self.label_4.setText(_translate("JBossDeserialVulnTool", "当前文件目录："))
        self.pBShowFile.setText(_translate("JBossDeserialVulnTool", "查看文件内容"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("JBossDeserialVulnTool", "文件目录管理"))

